blank_issues_enabled: true
contact_links:
  - name: Troubleshooting OpenRazer
    url: https://github.com/openrazer/openrazer/wiki/Troubleshooting
    about: Take a look here if your device appears as 'unsupported' or 'unrecognized'

  - name: My Razer hardware is misbehaving!
    url: https://github.com/openrazer/openrazer/issues/new/choose
    about: Create the issue on OpenRazer's repository for device specific bugs
