name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Python Dependencies
      uses: actions/cache@v4
      with:
        path: 'requirements.txt'
        key: python-deps-venv

    - name: Install Dependencies
      run: |
        sudo apt-get update

        # Python Lint
        sudo apt-get install pylint

        # Man
        sudo apt-get install scdoc

        # Build System
        sudo apt-get install meson

        # Locales
        sudo apt-get install gettext intltool

        # XDG Metainfo (AppStream)
        sudo apt-get install appstream

        # Install OpenRazer Python library for validation
        sudo add-apt-repository ppa:openrazer/daily
        sudo apt-get install python3-openrazer

        # Application Dependencies
        sudo apt-get install python3-gi gir1.2-gtk-3.0 gir1.2-appindicator3-0.1

        # Use virtual Python environment to use latest dependencies
        sudo apt install python3-venv
        python -m venv --system-site-packages venv
        source venv/bin/activate
        pip install pip-tools
        pip-sync

    - name: Validate JSON
      run: |
        ./scripts/validate-json.py

    - name: Validate Python
      run: |
        ./scripts/validate-py.sh

    - name: Validate QSS
      run: |
        ./scripts/validate-qss.py

    - name: Validate Manual
      run: |
        ./scripts/validate-scdoc.sh

    - name: Validate AppStream Metainfo
      run: |
        ./scripts/validate-metainfo.sh

    - name: Test Meson and Ninja
      run: |
        meson build --prefix=/tmp/pkg/
        ninja -C build install

    - name: Generate Locales
      run: |
        ./scripts/create-locales.sh

    - name: Build Locales
      run: |
        ./scripts/build-locales.sh

    - name: Create Artifact
      run: |
        ./scripts/packaging/ci-create-artifact.sh /tmp/dist

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: polychromatic-run${{github.run_number}}
        path: /tmp/dist/

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Python Dependencies
      uses: actions/cache@v4
      with:
        path: 'requirements.txt'
        key: python-deps-venv

    - name: Install Dependencies
      run: |
        sudo apt-get update

        # Build Dependencies
        sudo apt-get install gettext

        # Application Dependencies
        sudo apt-get install python3-colorama python3-colour python3-requests python3-setproctitle
        sudo apt-get install python3-gi gir1.2-gtk-3.0 gir1.2-appindicator3-0.1

        # Use virtual Python environment to use latest dependencies
        sudo apt install python3-venv
        python -m venv --system-site-packages venv
        source venv/bin/activate
        pip install pip-tools
        pip-sync

    - name: Install OpenRazer
      run: |
        git clone https://github.com/openrazer/openrazer --depth=1 "$GITHUB_WORKSPACE/openrazer"
        sudo add-apt-repository ppa:openrazer/daily
        sudo apt-get install openrazer-daemon python3-openrazer dbus-x11

    - name: Build Locales
      run: |
        ./scripts/build-locales.sh

    - name: Run Unit Tests
      run: |
        source venv/bin/activate
        ./tests/run.sh --verbose

    - name: Run Integration Tests with OpenRazer
      run: |
        eval $(sudo dbus-launch --sh-syntax)
        sudo -E ./tests/openrazer/run_daemon.sh "$GITHUB_WORKSPACE/openrazer"

  push_to_preview_ppa:
    name: 'Package / Debian'
    needs: [build, test]
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update

        # Build Dependencies
        sudo apt-get install meson gettext intltool

        # Debian Packaging
        sudo apt-get install debhelper devscripts

    - name: Test Debian Packaging
      run: |
        git clean -df
        git checkout .
        sed -i "s/noble/UNRELEASED/g" debian/changelog
        dpkg-buildpackage -S -us -uc -d
        lintian --tag-display-limit 0
        debuild -b

    - name: Upload to Launchpad
      if: ${{ github.event_name == 'push' && github.repository == 'polychromatic/polychromatic' && github.ref == 'refs/heads/master' }}
      run: |
        mkdir -p ~/.gnupg/
        chmod 700 ~/.gnupg
        printf "$BOT_GPG_KEY_BASE64" | base64 --decode > ~/.gnupg/private.key
        gpg --import ~/.gnupg/private.key
        git fetch --unshallow --tags
        ./scripts/packaging/prepare-preview-ppa.sh ./
      env:
        BOT_GPG_KEY_BASE64: ${{ secrets.BOT_GPG_KEY_BASE64 }}
